Traveli: Reservations List & Unbook/Delete Booking
romans-adi/travel-booking-frontend pull request #9
Opened 2023-10-01 03:40 UTC by romans-adi

For this PR reservations list and deleting booking functionality were implemented. The list of changes and updates:

### Reservations List Component & Item:

- Conditionally rendered the `ReservationListItem` components based on the availability of the `booking.date` property.
- `Fetches` data from the `API` when the component mounts.
- Implements the ability to `remove` a booking.
- Handles `loading` and `error` messages based on `Redux state`.
- Randomly `selects a background image` from the `list of places`.

### Redux and API Integration:

- Created Redux actions and reducers for `fetching` and `removing` bookings (`fetchBookings` and `removeBooking`).
- Integrated Redux state management for `bookings` into the `ReservationsList` component.
- Dispatched Redux actions to fetch `bookings`, `places`, and `travels` when the component mounts.
- Implemented the `handleUnbook` function to `remove a booking`.
- Displayed `loading` and `error` messages based on `Redux state`.

These changes were implemented concurrently with an update to the backend (for `Reservations Controller`).

2023-10-01 16:06 UTC, carreraprogrammer commented on src/pages/Reservations/ReservationsList.jsx
> +  const places = useSelector((state) => state.places.data);
I think it could be possible to use only the bookings variable to obtain the place data and the travel data. By now we are doing 3 API requests for only one page, but it is not necessary because the reservation is a linked table and could have all that information. What do you think? It also implies to change also the back-end api/v1/reservations to include travel.data and places.data

I would also like to change the name of the reducer to reservations instead of booking to maintain the readability.

2023-10-01 16:18 UTC, carreraprogrammer requested changes
Hi @romans-adi,

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next part, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 02:05 UTC, romans-adi commented on src/pages/Reservations/ReservationsList.jsx
> +  const places = useSelector((state) => state.places.data);
It's a good idea, indeed, to use the Redux store, and we are `already doing so`. This `data will be requested once`, and when we use `useSelector` to access `places`, `bookings`, and `travels` in this component, it will retrieve the data `from the Redux store without making new network requests`.

2023-10-03 02:08 UTC, romans-adi commented on src/pages/Reservations/ReservationsList.jsx
> +  const places = useSelector((state) => state.places.data);
In the situation where we want to retrieve only `travels` from the `store`, we would need to add an `additional column to the Travel table`, which, in turn, would `require us to update the Booking and Add Travel forms`.

2023-10-03 04:49 UTC, carreraprogrammer commented
# Approved! :medal_sports: 

Hi @carreraprogrammer, 

Your part in the project is complete! :shipit:
Congratulations! :rocket:
 
<img src="https://media2.giphy.com/media/l0HlMZrXA2H7aqpwI/giphy.gif?cid=ecf05e47847q11cews55teno7iu81bb60k45b3cpyr4gi2gx&ep=v1_gifs_search&rid=giphy.gif&ct=g"/>

## Highlights

- [x] All linters passed
- [x] Great work implementing booking functionality
- [x] Great work implementing changes 

Cheers, and Happy coding!👏👏👏
***
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 04:50 UTC, merged